### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by cirodev** [xerial/sqlite-jdbc#252]
Hi
when I try to connect an sqllite db using latest driver I get this exception

`java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
	at org.sqlite.core.NativeDB._open(Native Method)
	at org.sqlite.core.DB.open(DB.java:161)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at com.intellij.database.remote.jdbc.impl.RemoteDriverImpl.connect(RemoteDriverImpl.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`

this error is showed for all program like DbVisualizer or Intelli J .

Reading on the net would seem like a version problem. But nothing has changed by installing recommended versions such as sqlite-jdbc-3.8.11.2

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

on Windows 10 64 Bit

Thanks

**Comment by MartyIX** [comment]
I would try 3.20.0 (the latest release) as it should fix the problem you talk about (https://github.com/xerial/sqlite-jdbc/commit/8fb5e9248b6523b8fb3945cd5e6ac4efb88db73b). It helped in my case anyway.

HTH

**Comment by NudeCaveMan** [comment]
If I understood correctly - it became possible (?) now to use this driver in android applications. 

_2017-01-10: sqlite-jdbc-3.16.1
- Add experimental support for ppc64, armv5, v6 (Raspberry PI), v7 and android-arm._

But it's impossible to get connection in 3.20.0:

```
java.lang.UnsatisfiedLinkError: Couldn't load sqlitejdbc from loader dalvik.system.PathClassLoader[dexPath=/data/app/com.caveman.myapplication-1.apk,libraryPath=/data/app-lib/com.caveman.myapplication-1]: findLibrary returned null
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:365)
                                                       at java.lang.System.loadLibrary(System.java:535)
                                                       at org.sqlite.core.NativeDB.<clinit>(NativeDB.java:38)
                                                       at org.sqlite.core.CoreConnection.open(CoreConnection.java:211) 
                                                       at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76) 
                                                       at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:26) 
                                                       at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24) 
                                                       at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45) 
                                                       at org.sqlite.JDBC.createConnection(JDBC.java:114) 
                                                       at org.sqlite.JDBC.connect(JDBC.java:88) 
                                                       at java.sql.DriverManager.getConnection(DriverManager.java:175) 
                                                       at java.sql.DriverManager.getConnection(DriverManager.java:140) 
```

Regardless of how the driver is loaded:
`DriverManager.registerDriver((Driver) Class.forName("org.sqlite.JDBC").newInstance());`
or
`Class.forName("org.sqlite.JDBC");`

 an error occurs on the:
`Connection connection = DriverManager.getConnection("jdbc:sqlite:" + ...)`

**Comment by cirodev** [comment]
I tried with the version you indicated but the result is the same. Could it depend on the java version?

**Comment by MartyIX** [comment]
I inclination is to say "no". My problem was with Java 8 too. Maybe you have found a new bug. I'm not sure.

Sorry, that's all I know. I'm not a developer of the library. Hopefully, somebody else will help you with the problem :-)

**Comment by cirodev** [comment]
The problem was file permission. Infact if i open program as administrator all works fine. The problem persist beacuse i create a db with an user that is not administrator.

**Comment by gotson** [comment]
Seems like it was resolved, i will close this. Comment if necessary.
