### ISSUE TITLE
Prepared statements close/finalize on constraint violations.

### ISSUE THREAD

**Issue by zurgug** [xerial/sqlite-jdbc#74]
Use case:
We are creating a prepared statement outside a loop. Inside the loop we bind the values to each parameter and then execute the prepared statement. The loop is running over data being read from an external source.

Issue:
If the prepared statement has an exception (e.g. constraint violation) the rest of the loop produces "statement is not executing" errors.

Cause:
This is caused by the statement being finalized in DB.java

   execute(CoreStatement stmt, Object[] vals)

when step returns SQLITE_CONSTRAINT.

Workaround:
If an exception is thrown then recreate the prepared statement. This is not ideal as it means you can not easily use lambda's or try with resource.

**Comment by LukeWoodward** [comment]
[This StackOverflow question](http://stackoverflow.com/questions/40184674/sqlite-preparedstatement-finalized/40185846#40185846) has what looks to be a similar issue (if not the same), in that it also relates to constraint violations and closing/finalization of prepared statements.  The workaround I suggested in my answer to that question was to downgrade sqlite-jdbc to 3.8.11.2, which correctly reports constraint violation exceptions.

**Comment by LukeWoodward** [comment]
OK, so here's a repro for the exception I mentioned.  Only dependency is that the SQLite JDBC driver must be on the classpath:

```
package com.example;

import java.sql.*;

public class Main {
    public static void main(String[] args) throws Exception {
        DriverManager.registerDriver(new org.sqlite.JDBC());
        Connection conn = DriverManager.getConnection("jdbc:sqlite:");
        conn.createStatement().executeUpdate("CREATE TABLE test (a INT NOT NULL, PRIMARY KEY (a))");
        PreparedStatement stmt = conn.prepareStatement("INSERT INTO test (a) VALUES (1)");
        stmt.execute();
        stmt.execute();
    }
}
```

**Expected output:**
```
Exception in thread "main" java.sql.SQLException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: test.a)
    at org.sqlite.core.DB.newSQLException(DB.java:890)
    at org.sqlite.core.DB.newSQLException(DB.java:901)
    at org.sqlite.core.DB.execute(DB.java:810)
    at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:50)
    at com.example.Main.minimalRepro(Main.java:36)
    at com.example.Main.main(Main.java:10)
```
This is the actual output when running against sqlite-jdbc version 3.8.11.2.  This is perfectly acceptable: I've violated a constraint so I'd expect the exception message to tell me so.

**Actual output** with sqlite-jdbc version 3.14.2.1:
```
Exception in thread "main" java.sql.SQLException: The prepared statement has been finalized
    at org.sqlite.core.NativeDB.throwex(NativeDB.java:429)
    at org.sqlite.core.NativeDB.reset(Native Method)
    at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:57)
    at com.example.Main.minimalRepro(Main.java:36)
    at com.example.Main.main(Main.java:10)
```

**Comment by hillam** [comment]
+1

**Comment by sstangle73** [comment]
+1

**Comment by doe300** [comment]
Running the example code given by @LukeWoodward, I get this correct error:

    Exception in thread "main" org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: test.a)
      at org.sqlite.core.DB.newSQLException(DB.java:909)
      at org.sqlite.core.DB.newSQLException(DB.java:921)
      at org.sqlite.core.DB.execute(DB.java:825)
      at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:53)
      at org.sqlite.TestBug74.main(TestBug74.java:36)


Tested with latest SQLite JDBC 3.15.2-SNAPSHOT (e2d9f2e077450d2a0360074d4eb4a12a32d7e5b1).

**Comment by LukeWoodward** [comment]
Confirmed as fixed in version 3.15.1.

**Comment by fsvehla** [comment]
Still present in 3.15.1 when custom function use `error`

**Comment by psini** [comment]
Check if pointer is valid before call to reset() also on line 80 of JDBC3PreparedStatement is to change the line to  if (!success && pointer != 0) db.reset(pointer);

**Comment by gongzhang** [comment]
Still reproduced in `sqlite-jdbc-3.16.1`.

**Comment by coulanuk** [comment]
This issue is still present in sqlite-jdbc-3.21.

**Summary**

A prepared statement is opened for multiple insert operations on a table, but is unable to survive primary key violations.

If one "bad" insert fails due to a Primary Key violation, the prepared statement is unable to process subsequent "good" inserts.  The expected behaviour is that pkey violation should not close or finalize the prepared statement.
  
An exception "statement is not executing" is raised when calling pstmt.setString() on what should be a "good" insert.

Tracing the error into org.Sqlite.core.CorePreparedStatement the call is failing in checkOpen() pointer==0.

Please see example below:

	String url = "jdbc:sqlite:./test.db";
	String createtable = "CREATE TABLE dummy(ID text, VAL text, PRIMARY KEY(ID) )";
	String droptable   = "DROP TABLE dummy";
	String psSQL       = "INSERT INTO dummy (ID, VAL) VALUES (?,?)";
	String id = "123456789";
	String val = "FooBar";
	String id2 = "123456789";
	String val2 = "FooBar2";
	String id3 = "345678901";
	String val3 = "FooBar3";

	try {
		Connection conn = DriverManager.getConnection(url);
		Statement st= conn.createStatement();

		st.executeUpdate(createtable);
		PreparedStatement pst = conn.prepareStatement(psSQL);

		// 1 insert entry
		try {
			pst.setString(1, id);
			pst.setString(2, val);
			pst.executeUpdate();
			System.out.println("1st insert OK for " + id);
		} catch (Exception e) {
			System.out.println("1st insert Failed for " + id);
			e.printStackTrace();
		}

		// 2. insert duplicate entry with pkey violation
		try {
			pst.setString(1, id2);
			pst.setString(2, val2);
			pst.executeUpdate();
			System.out.println("2nd insert OK for " + id2);
		} catch (SQLException e) {
			System.out.println("2nd insert Failed for " + id2);
			e.printStackTrace();
		}

		// 3. try to insert 3rd value - exception raised is "statement is not executing" on pst.setString(1, id3)
		try {
			pst.setString(1, id3);
			pst.setString(2, val3);
			pst.executeUpdate();
			System.out.println("3 insert OK for " + id3);
		} catch (SQLException e) {
			System.out.println("3 insert Failed for " + id3);
			e.printStackTrace();
			isInsert2ok = false;
		}

		assertFalse("pst is closed", pst.isClosed());
		pst.close();
		st.executeUpdate(droptable);
		conn.close();

	} catch (SQLException e) {
		e.printStackTrace();
	}

**Comment by witmoca** [comment]
It looks to me as though the problem originates with the output of step (core/db:811):
The default action finalizes the statement. As the return code of step is either  SQLITE_ERROR ( in legacy code), SQLITE_CONSTRAINT or SQLITE_CONSTRAINT_FOREIGNKEY. The finalize statement appears to be used here because the legacy system requires a finalize before giving more detailed error information. See [http://www.sqlite.org/c3ref/step.htm](step) in the _Goofy Interface Alert_ section.

```        int statusCode = step(stmt.pointer);
        switch (statusCode) {
        case SQLITE_DONE:
            reset(stmt.pointer);
            ensureAutoCommit();
            return false;
        case SQLITE_ROW:
            return true;
        case SQLITE_BUSY:
        case SQLITE_LOCKED:
        case SQLITE_MISUSE:
            throw newSQLException(statusCode);
        default:
            finalize(stmt);
            throw newSQLException(statusCode);
        }
```

**Comment by witmoca** [comment]
Is it not possible to add SQLITE_CONSTRAINT to the switch case that handles the output of step (db:811)?

**Comment by b3nn0** [comment]
+1, SQLITE_CONSTRAINT should certainly be there.
SQLite doesn't close prepared statements in such a case, only SqliteJdbc does, which seems counter intuitive.

**Comment by xerial** [comment]
#74 will fixes this (3.23.1)
